version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icore-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=108.171.216.220
      - DATABASE_PORT=21033
      - DATABASE_NAME=icore-nest
      - DATABASE_SSL=false
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_LOGGING=true
      - DATABASE_SYNCHRONIZE=false
      - JWT_SECRET_KEY=your-secret-key
      - JWT_TTL=1h
      - S3_END_POINT=https://s3.us-east-005.backblazeb2.com
      - S3_KEY_ID=005153c6f68e9380000000007
      - S3_SECRET_KEY=K005TTX7ur5C5NIYTaaK7el7EC5QHdA
      - S3_BUCKET_NAME=educonnect-2
      - PORT=3000
  
  nginx:
    image: nginx
    container_name: nestjs-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "21081:80"
    depends_on:
      - nestjs-app